rcaelers/workrave

frontend/applets/gnome-shell/src/metadata.json.in

The applet works fine in Gnome 3.16.

Adds Gnome shell 3.16 support

---

CMakeLists.txt
README
frontend/apps/qt5/src/BreakWindow.cc
frontend/common/src/CMakeLists.txt

The included changes make workrave build again. I still get a segfault when I run the Qt5 frontend, though:
``` !gdb
$ cd frontend/apps/Qt5/src
$ gdb ./Workrave 
GNU gdb (Gentoo 7.9.1 vanilla) 7.9.1
…
(gdb) run
Starting program: /home/arne/Dokumente/eigenes/Programme/workrave/build/frontend/apps/qt5/src/Workrave 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
QSystemTrayIcon::setVisible: No Icon set
[New Thread 0x7fffe2a14700 (LWP 23660)]
[New Thread 0x7fffe995a700 (LWP 23659)]
[New Thread 0x7fffea366700 (LWP 23658)]
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff49d8dca in strlen () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff49d8dca in strlen () from /lib64/libc.so.6
#1  0x00007ffff5758cf9 in …
```

Builds again under GNU/Linux

---

configure.ac

Default action of PKG_CHECK_MODULES is to bail out if the version check is negative. But we still need to allow compilation, just do not forcibly enable C++11 features.

Fix compilation if gtkmm-3.0 version is less than 3.18.0

---

INSTALL

The packages glib-2.0,  glibmm-2.4 and gtkmm-2.4 don't exist any more, replaced with the packages I guessed.
Then started `./autogen.sh` (Ubuntu 15.10 64 bit), but I end up with this error:
frontend/applets/common/src/Makefile.am:10: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
`./configure` doesn't work like this:
...
checking pkg-config is at least version 0.9.0... yes
./configure: line 20275: syntax error near unexpected token `noext'

package changes in Linux install dependencies

---

.travis.yml

This should speed up the build as all Travis CI builds are
from scratch and generating dependency info is not of any help.

Add --disable-dependency-tracking for Travis CI

---

contrib/plot/workrave-dump

Here is a patch fixing the error described in #1224 at http://issues.workrave.org/show_bug.cgi?id=1224
Thanks for your time.
Best regards,

Fixed syntax error in workrave-dump perl script.Fix #1224

---

frontend/apps/gtkmm/src/TimerPreferencesPanel.cc

These controls where not greyed out if Enable timer checkbox on Rest break tab
was unchecked:
* Break duration
* Number of exercises
* Start restbreak when screen is locked
* Enable shuttting down the computer from the rest screen

Grey out all controls on Rest break=>Enable timer

---

frontend/gtkmm/src/Makefile.am

In Fedora we filter the output binaries with debug stripper and move them out
into separate packages. It does not like double slashes in the build process
erroring out with:
/usr/lib/rpm/debugedit: canonicalization unexpectedly shrank by one character
This fixes double slash during the build in:
... -I../../../frontend/plugin/distribution//gtkmm/src ...
Which is enough to silence this tool and the package now builds again.
For some reason, our upstream release monitor was mis-configured and Fedora
shipped fairly old version of workrave for some time. Not again, the next
version will be based on the current one and our monitor was fixed now!

Fixes debuginfo stripper 'canonicalization error'

---

frontend/applets/gnome-shell/src/extension.js

It is supposed to be "Mainloop" not "MainLoop".

Fixes a typo in code

---

frontend/applets/gnome-shell/src/extension.js
frontend/applets/gnome-shell/src/metadata.json.in

Adds support for Gnome shell 3.18
"Open Workrave" instead of just showing "Open"
Makes the DBusProxy call async so that it would not hang the gnome shell.

Adds support for Gnome Shell 3.18 and fixes an extension bug

---

frontend/gtkmm/src/BreakWindow.cc
frontend/gtkmm/src/BreakWindow.hh

I absolutely love Workrave and it's changed the way I work. There was only one thing bothering me so I've tried to fix it up. Please bear with me as I'm not a C developer and this is my first time working with GTK.
There's an option in preferences to disable the shut down / suspend options on the rest break panel's "sysoper" dropdown. If you disable this, you're left with a combobox that only contains the 'Lock' option.
I figured it would be nicer to have this be a button instead of a combobox. I've moved the logic that checks to see if the shutdownable is enabled further up the chain, and if it's disabled it draws a button instead of a combobox.
I'm not sure how to get the button to be the same width as the others (it's currently only the width of the word 'Lock') but aside from this it …

Don't use a combo box for sysoper on GTK frontend if shutdown is disabled

---

frontend/applets/gnome-shell/src/metadata.json.in

https://bugs.debian.org/822373

Make applet compatible with gnome-shell 3.20

---

backend/src/GSettingsConfigurator.hh

I had the headers for bot gconf and gsettings available and in the build, GConfConfigurator couldn't be found. Because it hasn't been defined, explicitly excluded :)

Fix ifdef in GSettings hh, so gconf headers work

---

INSTALL

Fix error where `./autogen.sh` would fail with a message about `AC_PROG_LIBTOOL` and `m4_pattern_allow`. Turns out, this is due to `libtool` not being installed on the system, so added `libtool` to list of dependencies.

Fix AC_PROG_LIBTOOL Error

---

frontend/applets/gnome-shell/src/metadata.json.in

As reported on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837214

Mark applet as compatible with GNOME 3.22

---

configure.ac
frontend/applets/gnome3/src/Makefile.am
frontend/applets/gnome3/src/org.gnome.panel.applet.WorkraveAppletFactory.service.in
frontend/applets/gnome3/src/v5/WorkraveApplet.c

* Make it build with the recently released libpanel-applet 3.22:
- Convert from out-of-process applet to in-process applet.
- Do not use `panel_applet_set_background_widget()` function.
- Instead, depend on libpanel-applet ≥ 3.16 where this function is no longer needed.
- Get the applets directory from pkg-config instead of using the hard-coded path (fix the existing pkg-config call).
* Also, fix the compiler warnings about implicitly declared functions.
See [this link](https://mail.gnome.org/archives/gnome-flashback-list/2016-July/msg00000.html) for details on what was removed in libpanel-applet 3.22.
The code will still work with libpanel-applet 3.16 and newer versions, but I have not tested pre-3.14 versions (though it *should* work with those versions too).

Multiple improvements for the GNOME Panel applet

---

frontend/applets/gnome3/src/Makefile.am

To have only a `.so` file, not also `.so.X`, `.so.X.Y`, `.so.X.Y.Z`.
This is a minor addition to my previous pull request.

Link the panel applet plugin with -module -avoid-version

---

README.md
backend/src/Configurator.cc
backend/src/Core.cc
backend/src/Core.hh
backend/src/DistributionSocketLink.cc
backend/src/GlibIniConfigurator.cc
backend/src/IdleLogManager.cc
backend/src/Statistics.cc
backend/src/Timer.cc
common/include/OSXHelpers.hh
common/src/StringUtil.cc
common/src/Util.cc
configure.ac
frontend/common/src/System.cc
frontend/common/src/TimerBoxControl.cc

I wasn't able to get things compiling on OS X anymore, so I'm having a go at making it do that.
Fixes:

[WIP] OS X fixes

---

backend/src/org.workrave.gschema.xml.in.in

Several users on GNOME (including me) [have reported this error](https://bugs.archlinux.org/task/56115) on startup in Workrave 1.10.18:
```
GLib-GIO-ERROR **: Settings schema 'org.workrave.monitor' does not contain a key named 'sensitivity'
```
This patch is a simple one that just adds the missing key to the schema, which resolves the issue for me.

Add missing key to gsettings

---

backend/src/win32/ghmac.c
build/cmake/README
build/cmake/backend/CMakeLists.txt
build/cmake/frontend/CMakeLists.txt
common/include/debug.hh
frontend/common/src/win32/W32DirectSoundPlayer.cc
frontend/common/src/win32/W32DirectSoundPlayer.hh
frontend/common/src/win32/W32Mixer.cc
frontend/common/src/win32/W32Shutdown.cc

- ghmac.c did not compile on MSVC because of missing casts.
- ghmac.c and W32Shutdown.cc were not included in the CMakeLists.
- README contained wrong steps on gettext/intltool dependency detection.
- debug.hh did not include <string> causing compilation errors.
- dxerr8.h does not exist in the advertised DirectX 9 SDK.
- Certain symbols do not exist in the MSVC SDK.
- W32Shutdown::shutdown did not return a value.

Fix compilation and linking errors on Windows with CMake

---

frontend/gtkmm/src/workrave.appdata.xml

This updates the AppStream metadata to a newer version, and fixes all compatibility problems detected by `appstreamcli validate workrave.appdata.xml`:
```
I - workrave.appdata.xml:workrave.desktop:18
Consider using a secure (HTTPS) URL for 'http://www.workrave.org/'
W - workrave.appdata.xml:workrave.desktop:5
SPDX license ID 'GPLv3+' is unknown.
E - workrave.appdata.xml:workrave.desktop:16
The screenshot does not contain any images.
I - workrave.appdata.xml:workrave.desktop:3
The id tag for "workrave.desktop" still contains a 'type' property, probably 
from an old conversion.
W - workrave.appdata.xml:workrave.desktop:3
The component ID is not a reverse domain-name. Please update the ID and that of 
the accompanying .desktop file to follow the latest version of the Desktop-Entry 
and …
```

Fix AppStream metadata validation

---

frontend/gtkmm/src/Makefile.am

Metainfo files should be installed into /usr/share/metainfo.

Don't use legacy path for AppStream metainfo file

---

README.md

I couldn't understand how to show the timers on Cinnamon panel and wanted to open an issue, but accidentally enabled timers by explicitly adding the workrave applet to a panel.
This info might save some time to the others.

Add info how to show timers on Cinnamon panel

---

configure.ac

"==" is an extension of bash and not supported in all shells.

Fix unportable shell construct

---

CMakeLists.txt
ui/applets/indicator/src/indicator-workrave.c
ui/apps/gtkmm/src/unix/IndicatorAppletMenu.cc

The libindicator package is deprecated in Debian. Applications
depending on it are expected to switch over to the fork (maintained
upstream and downstream): "libayatana-indicator".
libayatana-indicator is compatible successor library for libindicator.
ref. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895038

Use libayatana-indicator instead of libindicator

---

po/zh_CN.po

勿扰(do not disturb) is a more accurate translation for "Quiet", and it's the same word in zh_TW translation. https://github.com/rcaelers/workrave/blob/5615273e8117aa69bb50065f717b32b480cb1f45/po/zh_TW.po#L92

Correct zh-CN translation

---

README.md

Current link to download page uses an insecure HTTP site with no direct HTTPS equivalent, as the secure version doesn't have the www prefix. Changed the link to go directly to the secure page.

Change readme Windows download link to HTTPS

---

frontend/gtkmm/src/X11SystrayAppletWindow.cc

when **workrave** is started, systray applet shows just an icon (  [lamb](https://github.com/rcaelers/workrave/blob/branch_v1_10/frontend/common/share/images/workrave-icon-medium.png) ) , but should be timer indicator (to my mind), this patchset fix that issue

fix update applet icon for first start

---

CMakeLists.txt
libs/config/src/CMakeLists.txt

Workrave fails to build if BOOST_ROOT is given and no Boost headers are present in /usr/include.
Workrave fails to build if gcc >= 10.0.0 is used and Boost < 1.73.0 is required.
This patch fixes both issues.

Fix compilation with BOOST_ROOT

---

po/pt_BR.po

This **PR** improves the translation for Brazilian Portuguese by:
* Fixing some minor typos in previous messages
* Adding some of the missing messages
I'm not very familiar with `po` files, so I may have missed something. If that is the case, I'm glad to extend this **PR** as needed.

Add some missing messages for PT-BR in po file

---

ui/app/toolkits/gtkmm/BreakWindow.cc
ui/app/toolkits/gtkmm/platforms/unix/WaylandWindowManager.cc
ui/app/toolkits/gtkmm/platforms/unix/WaylandWindowManager.hh

wayland.xml: "When a client wants to destroy a wl_surface, they must destroy this role object before the wl_surface, otherwise a defunct_role_object error is sent."
Fixes: https://github.com/rcaelers/workrave/issues/550

Destroy zwlr_layer_surface_v1 before wl_surface

---

contrib/waybar-yambar-applets/README.md

Just fixing a typo. There was a missing backtick in the Markdown markup of README.md.

Fix markup typo in README.md for Waybar & Yambar applets

---

contrib/waybar-yambar-poss-other-applets/sfwbar/workrave.widget

This allows Workrave widget timers to be styled with a "workrave_timer" widget style, which can be used in the CSS used to style Sfwbar.

Minor update to sfwbar Workrave widget

---

ui/app/org.workrave.gui.gschema.xml.in

It was crashing with the following error:
`(process:448781): GLib-GIO-ERROR **: 04:00:11.243: Settings schema 'org.workrave.gui' does not contain a key named 'theme-dark'`

Fix Linux crash after commit d560e97 (auto dark mode), add missing dconf

---

ui/applets/gnome-shell-45/src/metadata.json.in

This is just to fix this bug: https://github.com/rcaelers/workrave/issues/582
It's a *very* simple fix.

Update metadata.json.in to fix bug #582

---

libs/input-monitor/src/unix/WaylandInputMonitor.cc
libs/input-monitor/src/unix/protocols/ext-idle-notify-v1.xml

This uses [version 2 of the ext-idle-notify protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/commit/20bcf732a9a173ae7d437882159fb7ababb4713e) where possible. If version 2 is unavailable, Workrave will fallback to using the older version of the protocol that does not ignore idle inhibitors.
This is a fixed version of the pull request that I had mangled due to a botched rebase: https://github.com/rcaelers/workrave/pull/590

Allow Workrave to ignore idle inhibitors if possible

---

contrib/waybar-yambar-poss-other-applets/README.md
contrib/waybar-yambar-poss-other-applets/swaybar/workrave-swaybar.sh
contrib/waybar-yambar-poss-other-applets/swaybar/workrave_swaybar_gen_json.py

This adds scripts that both allow Workrave's status to appear on Sway's swaybar and allow the Workrave status window to open when clicking on Workrave's status in swaybar. The README has been edited to document this.

Add examples of usage with swaybar

---

ui/app/toolkits/gtkmm/platforms/unix/AppIndicatorMenu.cc
ui/app/toolkits/gtkmm/platforms/unix/AppIndicatorMenu.hh

Fixes #556
A pointer to the D-Bus root menu item is updated at each change of the mode, but AppIndicator doesn't get this pointer, being left with an invalid one assigned during its initialization.
This patch fixes it by reassigning the pointer at each change of the mode.

Fix an empty AppIndicator menu

---

ui/app/toolkits/gtkmm/MainWindow.cc
ui/app/toolkits/gtkmm/platforms/unix/AppIndicatorMenu.cc
ui/app/toolkits/gtkmm/platforms/unix/AppIndicatorMenu.hh

Fixes #612
Short unavailabilities of the system tray cause the status window to appear. This can happen, when Sway reloads or shortly after waking a monitor from sleep.
The window has to be closed, which is cumbersome.
This patch fixes this by introducing a short delay to showing the window, which gives the system tray time to reappear.
It also checks, if there is any monitor to show the window on, before showing it, mainly for not setting the status window setting to enabled, which causes it to reappear after waking up a monitor.

Fix open_window on system tray reloads
