rcaelers/workrave

configure.ac, m4/ax_cxx_compile_stdcxx_11.m4, m4/intltool.m4, m4/libtool.m4, m4/ltoptions.m4, m4/ltsugar.m4, m4/ltversion.m4, m4/lt~obsolete.m4, po/Makefile.in.in
After Gnome and gtkmm 3.18 releases, build with C++11 is required.
=> Build with C++11 if gtkmm >= 3.18.0

po/zh_TW.po
1. Unify translations for Quiet, Suspend, Micro-break, Rest-break
2. Fill in missing translations.
=> Traditional Chinese translation update

README.md
I create this pull request, because issues are not enabled in this Github repository.
please enable issues in settings, so we can discuss this in the right place
=>  not working with wayland on Ubuntu 17.10

frontend/applets/gnome-shell/src/extension.js
Signed-off-by: Timo Jyrinki <timo.jyrinki@iki.fi>
=> Do not force default gettext domain. (Closes: #110)

po/pt.po
=> New translation file

frontend/common/include/credits.h, po/LINGUAS, po/id.po
=> Added Indonesian translation

README.md
It took me forever to figure out the most elementary ways workrave interacts with my system. This adds a primer to people who might want to script.
Btw, the Troubleshooting entry might be better suited to the FAQ on the website.
=> Add some technical information to README

README.md
- Added installation command for Ubuntu and Debian users + Reformatted the commands section a little to match the pattern
- While this may be trivial to experienced users, for someone fairly new to the linux env, these little changes could avoid some confusion in the beginning
=> Add installation command for Ubuntu + debian users

README.md
Changing main site link at top of readme to use HTTPS address instead of insecure (and different) HTTP link. Sorry for missing this from #296
=> Change readme site link to HTTPS

frontend/applets/gnome-shell/src/metadata.json.in
Tested to be working without further changes.
=> Add 41 to supported GNOME Shell versions

ui/apps/gtkmm/dist/win32/setup.iss.in
I think this resolves #349, but I've never worked with inno before. If this isn't correct, I wouldn't be surprised. 
Not tested as I haven't set up the compiler yet
=> Add Version Entry to Inno Setup

po/fa.po
Hello
Please merge this new tranlation for Persian.
I also manualy move the `.mo` file to my system locales directory. But some parts of Workrave GNOME extention not changed. I don't know why.
Thanks!
=> Update Persian translation

README.md
=> Add Link to NEWS in Readme

po/zh_CN.po
I localized zh_CN.po from scratch based on https://github.com/rcaelers/workrave/blob/main/po/workrave.pot
=> Overhaul of zh-CN.po

po/zh_CN.po
I made revisions to zh-cn.po based on suggestion from @greyovo and own findings
=> Update zh-CN.po 

libs/core/include/core/ICore.hh, libs/core/src/Core.hh, ui/app/platforms/windows/WindowsStatusIcon.cc, ui/app/platforms/windows/WindowsStatusIcon.hh, ui/app/toolkits/gtkmm/MainWindow.cc
https://github.com/rcaelers/workrave/issues/241
=> Prevent click on mainwindow and windowsstatusicon when break is_taking

po/es.po
Signed-off-by: Cristian Othón Martínez Vera <cfuga@cfuga.mx>
=> Update Spanish translation for branch_v1_10

po/fr.po
Addition of French translations and corrections
=> Addition of French translations and corrections

contrib/waybar-yambar-poss-other-applets/README.md, contrib/waybar-yambar-poss-other-applets/eww/eww-workrave.scss, contrib/waybar-yambar-poss-other-applets/eww/eww-workrave.yuck, contrib/waybar-yambar-poss-other-applets/sfwbar/workrave.css, contrib/waybar-yambar-poss-other-applets/sfwbar/workrave.widget
I have created a couple EWW widgets that can be used on their own or included into someone's pre-existing EWW setup. I've also added files to create a Workrave applet for Sfwbar.
=> Add example usages of Workrave with EWW and Sfwbar

README.md
Small PR - Commit c14c5d68fbc802dc9d0d969e939f355647400439 moved `dbus-example.py`. This PR adjusts sources to changes.
=> Update dbus example

ui/app/toolkits/gtkmm/platforms/unix/AppIndicatorMenu.cc
=> Fix invalid AppIndicator icons
